from __future__ import annotations

from dataclasses import dataclass
from typing import Literal

from redline.models import ReasonCode


@dataclass(frozen=True)
class ReasonMeta:
    severity: Literal["blocking", "advisory"]
    recoverable: bool
    summary: str


_REASON_SUMMARIES: dict[ReasonCode, tuple[Literal["blocking", "advisory"], bool, str]] = {
    ReasonCode.PASS: ("advisory", True, "verification passed"),
    ReasonCode.NEW_BLOCK_BREACH: ("blocking", True, "candidate introduced a new blocking probe breach"),
    ReasonCode.RECEIPT_MISMATCH: ("blocking", True, "receipt hash or receipt-bound projection changed"),
    ReasonCode.PROOF_HASH_MISMATCH: ("blocking", True, "proof sidecar, proof hash, or proof replay changed"),
    ReasonCode.LEDGER_CHAIN_BROKEN: ("blocking", True, "issuance or audit ledger hash chain is broken"),
    ReasonCode.CHECKPOINT_MISMATCH: ("blocking", True, "ledger checkpoint hash, tail, or coverage changed"),
    ReasonCode.EXECUTION_LEDGER_BROKEN: ("blocking", True, "execution ledger hash chain or entry binding is broken"),
    ReasonCode.MERKLE_INCLUSION_FAILED: ("blocking", True, "merkle root or inclusion proof does not cover the expected leaf"),
    ReasonCode.APPROVAL_LINK_MISMATCH: ("blocking", True, "approval hash no longer links to the execution or decision record"),
    ReasonCode.APPROVAL_CONSUMED: ("blocking", True, "single-use approval was already consumed"),
    ReasonCode.APPROVAL_EXPIRED: ("blocking", True, "approval TTL expired before execution"),
    ReasonCode.CHAIN_LINK_MISMATCH: ("blocking", True, "cross-artifact chain link does not match"),
    ReasonCode.BASELINE_UNCHAINED: ("advisory", True, "PASS receipt lacks trusted ledger attestation"),
    ReasonCode.BASELINE_GENESIS: ("advisory", True, "baseline is genesis and needs a prior-chain anchor for production publish"),
    ReasonCode.COVERAGE_INCOMPLETE: ("blocking", True, "required verdict proof coverage is incomplete"),
    ReasonCode.PROBE_ERROR: ("blocking", True, "a probe failed to evaluate cleanly"),
    ReasonCode.ENGINE_FAILURE: ("blocking", True, "deterministic engine failed or could not replay"),
    ReasonCode.DATA_MISSING: ("blocking", True, "required file, artifact, or field is missing"),
    ReasonCode.CALIBRATION_FAILED: ("blocking", True, "baseline calibration failed"),
    ReasonCode.BASELINE_BREACHES: ("blocking", True, "baseline itself breaches blocking probes"),
    ReasonCode.BASELINE_UNRUNNABLE: ("blocking", True, "baseline could not run"),
    ReasonCode.NONFINITE_VALUE: ("blocking", True, "canonical data contained a non-finite numeric value"),
    ReasonCode.ENGINE_IDENTITY_MISMATCH: ("blocking", True, "engine source, runner lock, or replay identity drifted"),
    ReasonCode.CANDIDATE_SANDBOX_VIOLATION: ("blocking", False, "candidate attempted a sandbox-forbidden operation"),
    ReasonCode.VERDICT_PATH_VIOLATION: ("blocking", False, "verdict path imported or used forbidden capabilities"),
    ReasonCode.RECEIPT_BINDING_FAILED: ("blocking", True, "package, identity lock, spec, or suite binding failed"),
    ReasonCode.SPONSOR_READBACK_MISMATCH: ("blocking", True, "sponsor read-back payload does not match local evidence"),
    ReasonCode.SPONSOR_EVIDENCE_UNVERIFIED: ("blocking", True, "sponsor evidence is missing or not independently verified"),
    ReasonCode.UNVERIFIED_NO_VERDICT: ("blocking", True, "verification was integrity-only and cannot authorize a verdict"),
    ReasonCode.FILE_NOT_FOUND: ("blocking", True, "input file does not exist"),
    ReasonCode.PARSE_ERROR: ("blocking", True, "input file could not be parsed"),
    ReasonCode.SCHEMA_INVALID: ("blocking", True, "input did not match the required schema"),
    ReasonCode.VERSION_UNSUPPORTED: ("blocking", True, "input schema or receipt version is unsupported"),
    ReasonCode.OUT_OF_SCOPE: ("blocking", True, "requested operation is outside the supported contract"),
}


REASON_META: dict[ReasonCode, ReasonMeta] = {
    code: ReasonMeta(severity=severity, recoverable=recoverable, summary=f"{code.value}: {summary}")
    for code, (severity, recoverable, summary) in _REASON_SUMMARIES.items()
}

if set(REASON_META) != set(ReasonCode):
    missing = sorted(code.value for code in set(ReasonCode) - set(REASON_META))
    extra = sorted(code.value for code in set(REASON_META) - set(ReasonCode))
    raise RuntimeError(f"ReasonCode metadata drift: missing={missing} extra={extra}")


def render_violation_catalog() -> str:
    lines = [
        "# Violation Codes",
        "",
        "Generated from `redline.violations.REASON_META`.",
        "Do not edit this file by hand; run `uv run python scripts/gen-violation-catalog.py`.",
        "",
        "| Code | Severity | Recoverable | Summary |",
        "|---|---|---|---|",
    ]
    for code in ReasonCode:
        meta = REASON_META[code]
        recoverable = "true" if meta.recoverable else "false"
        lines.append(f"| `{code.value}` | `{meta.severity}` | `{recoverable}` | {meta.summary} |")
    return "\n".join(lines) + "\n"
